name: sonidos_de_lluvia_para_dormir
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  camera: ^0.11.0+2
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  gdpr_dialog: ^2.1.1
  google_mobile_ads: ^5.2.0
  in_app_review: ^2.0.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  soundpool: ^2.4.1
  url_launcher: ^6.1.6

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # a

flutter:

  uses-material-design: true
  assets:
    - lib/assets/fondoSplash.jpg
    - lib/assets/banner.jpg
    - lib/assets/nubes.jpg
    - lib/assets/venti.jpg
    - lib/assets/giphy.gif

    - assets/icon/logo.png
    - lib/assets/images/
    - lib/assets/sounds/
    - lib/assets/videos/
    - lib/assets/imagesFan/

    - lib/assets/icon/senal_icon 512x512.png
    - lib/assets/icon/ExamenPracticoLogo.png
    - lib/assets/icon/preguntasLogo.png    
    - lib/assets/icon/examenMotoLogo.png        
    - lib/assets/icon/senialesEEUUlogo.png     